### LLM Setting ### 
CHAT_MODEL: 
  api_key: ${OPENAI_API_KEY}
  api_base: ${OPENAI_BASE_URL}
  model_id: qwen3-235b-a22b


### Embedding Model Setting ##
EMBEDDING_MODEL:
  api_key: ${EMBEDDING_API_KEY}
  api_base: ${EMBEDDING_API_BASE}
  model_id: text-embedding-v3


### ReRank Setting ### 
RERANK_MODEL: 
  api_key: ${RERANK_API_KEY}
  api_base: ${RERANK_API_BASE}
  model_id: gte-rerank-v2



### VectorStore Setting ###
VECTOR_STORE:
  type: lancedb
  persist_directory: ./app/.local_db


### Playwright Setting ###
CRAWLER:
  # Maximum time in seconds to wait for requests to complete
  timeout: 30.0
  # Run browser in headless mode (no GUI)
  headless: true
  # Enable verbose logging
  verbose: false
  # Enable response caching
  cache_enabled: true




